### PR TITLE
update lerna version

### PR DESCRIPTION
**Pull request by mburleigh**
Installed version has to match version specified in lerna.json

### CODE REVIEW

**Comment by tonyanziano** [comment]
Thanks @mburleigh!

**Comment by mburleigh** [comment]
@tonyanziano - the CLA bot never kicked in and the link to the CLA in contributing.md is broken. How can I sign the CLA? Thanks!

**Comment by tonyanziano** [comment]
@mburleigh 

Hmm, the bot should've prompted you or passed.

Maybe you can re-submit a new PR with the exact same change and we'll see if that fixes it? If you want you can also update the CLA link in the README. (https://cla.opensource.microsoft.com/)

**Comment by mburleigh** [comment]
Thanks @tonyanziano; signing in on https://cla.opensource.microsoft.com/ cleared up my CLA issue. PR 1002 fixes the link in contributing.md

**Comment by tonyanziano** [comment]
Awesome! I'll merge it in when the checks pass. 👍

**Pull request merged**
