### PR TITLE
[ISSUE#1898][MAS4.2.1] [Screen Reader-Services] When the user "Open any pop-up or dialog", voiceover is reading the unnecessary information for them. 

### LINKED ISSUE #1898: [MAS4.2.1] [Screen Reader-Services] When the user "Open any pop-up or dialog", voiceover is reading the unnecessary information for them.
**Actual Result:**
When the user opens "Sign in with your Azure account" button, voiceover announces unnecessary information for the pop-up or dialog box.
Voiceover is reading as "Close and 6 more items" when "Sign in with your Azure account" pop-up appears.

**Expected Result:**
The voiceover should announce the information about the dialog only without providing irrelevent information.

**Note:**
Same issue observed for each and every dialog box or pop-ups throughout the application.

**Repro Steps:**
1. Open the Bot Framework V4 Emulator.
2. Welcome tab screen gets opened.
3. Navigate to the "Sign in with your Azure account" button and activate it.
4. Observe the issue.

**User Impact:**
Users who rely on screen readers will be affected if the screen reader is reading the inappropriate info for control then the screen reader users will be misguide the info for control

**Test Environment:**
OS: MacOs Version 10.15
Application: Bot Framework V4 Emulator (Version 4.5.2-80829)

**Impacted MAS Link:**
[https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={a12f3779-bdf1-40c2-bbcc-0e314ea94858}](url)

**Attachment:**
[Unnecessary info.zip](https://github.com/microsoft/BotFramework-Emulator/files/3685952/Unnecessary.info.zip)
[Extra information.zip](https://github.com/microsoft/BotFramework-Emulator/files/3895364/Extra.information.zip)

### PR DESCRIPTION
**Pull request by Aliandi**
Fixes #1898

#### Description
This pull request fixes how the **Voiceover** announces the information for the pop-up or dialog box.

The **Dialog** component used the attribute `aria-labelledby` to indicates its title. This attribute in combination with the role `dialog` makes the **Voiceover** reads a count of the elements of the dialog.

To fix the issue we update the component to use an `aria-label` instead of `aria-labelledby`. This way the reader read the title of the dialog and the first element focusable. 

#### Changes Made
- Update the **Dialog** component to use an `aria-label` instead of `aria-labelledby` attribute.

#### Testing
Screen Shot 2019-11-22 at 4 18 56 PM

Screen Shot 2019-11-22 at 4 19 27 PM

### CODE REVIEW

**Comment by corinagum** [comment]
Please disregard my comments about the video behavior. After looking at this again with tonyanziano, I agree that the behavior has been fixed. My apologies! 

I am happy to merge this in once the changelog entry and issue number have been fixed. Thank you!

**Comment by corinagum** [comment]
Sorry to keep going back and forth on this -- I am going to contact the a11y time about this one, so let's not merge it in yet. I actually think that the behavior is fixed in the nightly, and it would be best to not take this PR to maintain the fixed behavior. 
The dialog is read out by the narrator, but I think that's what we expect. tonyanziano made the following clip as an example: https://codepen.io/Fignewton5/pen/GRRLXEB

**Comment by denscollo** [comment]
Ok, thanks @corinagum! We'll wait to see if it's already solved and if not we'll add the changelog entry 😄

**Comment by corinagum** [comment]
@denscollo looks like the behavior is still incorrect, however the a11y team hasn't uploaded the latest video yet. Let's wait and see that before proceeding, thanks!

**Comment by denscollo** [comment]
@corinagum Ok! Let us know and we'll apply any change needed. Thanks!

**Comment by tonyanziano** [comment]
@denscollo Thanks for the help on this one. We took the conversation offline with the a11y team, and reached the conclusion that the behavior is fine and we are good to close the issue.

**Pull request closed without merging**
