### PR TITLE
Jwilaby/debugging doc

### PR DESCRIPTION
**Pull request by justinwilaby**
Related to #1443 - This PR provides:

1. A general purpose Markdown Renderer page
2. A new help menu item for getting started with debugging your bot via channels
3. A link on the Welcome page (when in sidecar debug mode) to the same help document

To test:
Checkout the branch and change [this line](https://github.com/Microsoft/BotFramework-Emulator/blob/jwilaby/debugging-doc/packages/app/shared/src/constants/sharedConstants.ts#L183) to use `https://raw.githubusercontent.com/Microsoft/BotFramework-Emulator/jwilaby/debugging-doc/content/CHANNELS.md`

**note** The images in the current document do not render (non-standard MD). This document is a placeholder and will change once we engage with the documents team.

Screen Shot 2019-04-25 at 11 52 21 AM
image

### CODE REVIEW

**Comment by cwhitten** [comment]
It looks like the Bot Inspector heading got bumped to the right a bit. It was flush with the other headings.

@mewa1024 and I discussed adding the link in the area where the `My Bots` box lives in Emulator mode. Though right next to the (BETA) label it seems a more discoverable.

**Comment by mewa1024** [comment]
So we’re not displaying the sidecar doc as it’s own tab, similarly to VS Code’s Release Notes (Help > Release notes)?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tonyanziano** [comment]
@mewa1024 From the first screenshot it appears to belong to its own tab:

image

**Comment by tonyanziano** [comment]
@justinwilaby I just noticed, you probably want to [go to this function, get iconClass()](https://github.com/Microsoft/BotFramework-Emulator/blob/master/packages/app/client/src/ui/shell/mdi/tab/tab.tsx#L155) inside of `tab.tsx` and add the document id for your docs page as a case right above `welcome-page` so that the icon for that doc tab defaults to the BF icon.

**Comment by justinwilaby** [comment]
> So we’re not displaying the sidecar doc as it’s own tab, similarly to VS Code’s Release Notes (Help > Release notes)? Get Outlook for iOS<https://aka.ms/o0ukef>
> […](#)
> ________________________________ From: Chris Whitten <notifications@github.com> Sent: Thursday, April 25, 2019 12:07:38 PM To: Microsoft/BotFramework-Emulator Cc: Melanie Wang; Mention Subject: Re: [Microsoft/BotFramework-Emulator] Jwilaby/debugging doc (#1463) It looks like the Bot Inspector heading got bumped to the right a bit. It was flush with the other headings. @mewa1024<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmewa1024&data=01%7C01%7Cmewa%40microsoft.com%7Cf9528e4907d24a18c14e08d6c9b1496d%7C72f988bf86f141af91ab2d7cd011db47%7C1&sdata=07i2EAZYwG7JyDdKsg7C%2BLYIxtLNkykexZd2F3Mr8NY%3D&reserved=0> and I discussed adding the link in the area where the My Bots box lives in Emulator mode. Though right next to the (BETA) label it seems a more discoverable. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2FBotFramework-Emulator%2Fpull%2F1463%23issuecomment-486800422&data=01%7C01%7Cmewa%40microsoft.com%7Cf9528e4907d24a18c14e08d6c9b1496d%7C72f988bf86f141af91ab2d7cd011db47%7C1&sdata=FkyC8gi0u8DGIyYSSWLteEHtinZsJ0aYHqPyQxIicOs%3D&reserved=0>, or mute the thread<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJL7AJWOFPGSAIHODEOFYUTPSH6PVANCNFSM4HIPYPBQ&data=01%7C01%7Cmewa%40microsoft.com%7Cf9528e4907d24a18c14e08d6c9b1496d%7C72f988bf86f141af91ab2d7cd011db47%7C1&sdata=d0EtIhNWr5f9kvIOSrRiyQVWGXX4mCNib52U%2FOlE%2B%2Bg%3D&reserved=0>.

Yes we are, take a look at the first screenshot. Chris was commenting about the placement of the link to that tabbed document next to the (BETA) text

**Comment by mewa1024** [comment]
@cwhitten I was thinking the sidecar doc would be more like this and that we could leave the Welcome page as is: 

sample debugging doc

**Comment by cwhitten** [comment]
@mewa1024 Recall our discussion that much of the Welcome Page interactions are specific to both .bot files and Emulator mode. We decided that hiding these elements was the right thing to do and replacing it with a link that would open up documentation in a new tab (like VSCode) on how to get started in the debug mode. I don't think we should mix product functionality (Open bot) with reference material in this sense. This is living, editable documentation that is markdown. This is how VSCode does their release notes & their tabbed material via their help menu. We can start doing the same.

**Pull request merged**
