### PR TITLE
 [ISSUE#1569] When a second livechat is started there are no conversation update activities

### LINKED ISSUE #1569: When a second livechat is started there are no conversation update activities
## Version
Emulator 4.4

## Describe the bug
When a livechat is started, closed, and then reopened from the endpoint sidebar, it starts the same chat instead of creating a new livechat.

## To Reproduce
1. Open a bot
2. Open the settings page
3. Close the bot
4. Open the bot from the endpoint menu

noConvUpdate

## Expected behavior
It should restart the conversation.

## Possible solution
We've found that if we remove this `if`, the emulator works as expected and it does not affect the behavior of any existing functionality. This is because when opening the bot from the endpoint menu, `shouldStartNewConversation` is always `false`.

```
componentWillMount() {
    window.addEventListener('keydown', this.keyboardEventListener);
    if (this.shouldStartNewConversation()) {
      this.startNewConversation();
    }
  }
```
Is there a reason for that `if` to be there? Could we delete it? If so, we will be uploading a PR with that solution.

### PR DESCRIPTION
**Pull request by Aliandi**
Fixes #1569 

### Changes made
- We removed the line on the `componentWillMount` that checked with the method `shouldStartNewConversation` if a new chat should be started because this was causing the incorrect behavior
- We removed the `shouldStartNewConversation` method
- We added some files that were commited with linting errors that prevented the branch from building.

### CODE REVIEW

**Comment by justinwilaby** [comment]
I'm not able to repro the problem this PR is attempting to solve. I'm opening 2 livechat instances of the same endpoint and am seeing conversation updates as expected.

What are the repro steps for this?

**Comment by Aliandi** [comment]
@justinwilaby we are looking at what you said.
Repro steps:
1.     Open a bot
2.     Open the settings page
3.     Close the bot
4.     Open the bot from the endpoint menu

imagen

**Comment by justinwilaby** [comment]
@Aliandi - Try this and let me know if you still see the same issue:

1. Open a bot and let the default conversation begin
2. right-click on the first endpoint in the list and choose "Open in Emulator"

I'm seeing the second conversation start with conversation updates as expected. If this is true for you as well, I think simply matching the functionality with what's in the right-click menu might be a reasonable approach here.

**Comment by Aliandi** [comment]
@justinwilaby We've added the method again but with a logic change and it seems to work for all the cases you've mentioned.

**Comment by justinwilaby** [comment]
@Aliandi - The latest changes seem to break the "restart conversation" button.

When I click "restart conversation", the chat is not cleared and 2 more conversation updates are shown.

**Comment by justinwilaby** [comment]
@Aliandi -

I'm seeing a different repro for this problem. The steps I have are:

1. Open a botfile from the welcome page and let the default conversation begin.
2. Open the same botfile from the welcome page and let the default conversation begin
**Observe** 2 conversations with the same endpoint are now displayed and conversation updates are working as expected
3. Click on the first endpoint in the services pane.
** Observer** A 3rd conversation tab is open which contains duplicate activities.

**expected behavior**
Clicking on the first endpoint in the services pane should set focus to the corresponding conversation instead of spawning another tab.

Also, opening the same botfile should either set focus to the conversation that is active for that botfile or start a conversation with the first endpoint in the services pane for that botfile.

**Comment by Aliandi** [comment]
@justinwilaby 
I am being able to repro opening a botfile twice, but not the issues with restart conversation or endpoint not leading to the correct conversation.

**Comment by Aliandi** [comment]
Hey @justinwilaby, I've been testing the bug and was able to repro with a previous version of the emulator. I think the best approach is to create an issue with that, and we can tackle that there.
Also, regarding the other two bugs, are these steps right?
Restart new conversation:
TestingIssue1

Endpoint opening a new chat:
TestingIssue3

**Comment by justinwilaby** [comment]
@Aliandi -
We've discovered an engineering issue that prevents us from restarting a conversation with a new userId when more than 1 chat tab is open. We're going to triage this and determine the best course of action. In the meantime, I think we should hold off on this particular PR.

**Comment by Aliandi** [comment]
Ok @justinwilaby! Let us now if we can help with anything!

**Comment by tonyanziano** [comment]
This might have been fixed recently as there has been a lot of work around starting and restarting conversations.

@justinwilaby or @denscollo can you try to repro this on current master and see if it was resolved?

If the issue is gone we can close this PR, otherwise we can take a look at how we want to integrate this change with master.

**Comment by denscollo** [comment]
@tonyanziano Sure, we'll run some tests and see if it's fixed or not and let you know!

**Comment by tonyanziano** [comment]
@denscollo Any update on if this issue has been resolved or not?

**Comment by denscollo** [comment]
@tonyanziano Yes! We tested it on master and it works perfectly. This PR can be closed!

**Comment by tonyanziano** [comment]
Awesome, thanks!

**Pull request closed without merging**
