### PR TITLE
allow for toggling devtools in development env

### PR DESCRIPTION
**Pull request by a-b-r-o-w-n**

### CODE REVIEW

**Comment by justinwilaby** [comment]
Since the emulator uses an old version of Chrome with a less useful dev tools, we removed this 2 months ago in favor of launching with the flag `--remote-debugging-port=<port>` and using `chrome://inspect` instead. This also allows us to see and debug all instances of `<WebView>`

**Comment by a-b-r-o-w-n** [comment]
@justinwilaby That is still an option in this change. However, using the remote debugger, I was unable to use the dom inspection feature, which is really useful when dealing with the webchat component.

**Comment by justinwilaby** [comment]
#888 explicitly removed this menu option as a design decision. Putting it back in should probably go through a design review/approval first.

**Comment by a-b-r-o-w-n** [comment]
Ok. I'll close for now, but I'd like to revisit at some point. I think having the keybinding open up chrome's devtools would still be nice.

**Pull request closed without merging**
