### PR TITLE
Studio shell

### PR DESCRIPTION
**Pull request by compulim**
Add shell and enclose the emulator

### CODE REVIEW

**Comment by eanders-MS** [comment]
Looks like this PR is against master. Let's keep all the studio stuff in the studio branch for now. We're going to have to make interim emulator releases in the meantime.

**Comment by compulim** [comment]
Working on a new PR, hold on.

**Comment by eanders-MS** [comment]
OK. I was going to leave a comment: Please use camelCase on directory names (unless they're abbreviations like UI). E.g.: `Integration` -> `integration`

**Comment by eanders-MS** [comment]
Same for filenames: `BotChatEditor.js` -> `botChatEditor.js`

**Comment by eanders-MS** [comment]
All new source files need the copyright notice at the top.

**Pull request closed without merging**
