### PR TITLE
Fixed shrinking of tab icon on sidecar docs page.

### PR DESCRIPTION
**Pull request by tonyanziano**
**Before:**
image

**After:**
image

### CODE REVIEW

**Comment by cwhitten** [comment]
The failing test in CI is odd. It seems unrelated.

**Comment by justinwilaby** [comment]
I fixed the logic that fails the unit test here: https://github.com/microsoft/BotFramework-Emulator/pull/1559/commits/d9ae26d191e678536a9f67e3e8ce96e24ad973ce

**Comment by cwhitten** [comment]
Ah, thank you @justinwilaby.

**Comment by corinagum** [comment]
This change is awesome. The old icons bothered me a lot. :D

**Pull request merged**
