### PR TITLE
Update Emulator for Ngrok v3 Support

### LINKED ISSUE #2389: Failed to spawn ngrok
## Version
What version of the Emulator are you using.
4.14.1-302259

## Describe the bug
Give a clear and concise description of what the bug is.
ngrok is not spawning. Trying to connect to a bot hosted in Azure

## To Reproduce
1. Path to ngrok set to '/snap/ngrok/current/ngrok'
2. Open remote bot (saved as .bot)
3. Error is in log Failed to spawn ngrok. Please go to the Ngrok Status Viewer and download the log file for a more detailed view of the error.{"error_code":102,"status_code":400,"msg":"invalid tunnel configuration","details":{"err":"yaml: unmarshal errors:\n line 1: field region not found in type config.HTTPv2Tunnel\n line 1: field path not found in type config.HTTPv2Tunnel"}}
[17:05:33]Error: The bot is remote, but the service URL is localhost. Without tunneling software you will not receive replies.

## Expected behavior
Give a clear and concise description of what you expected to happen.
ngrok spawns and I am able to connect to bot (this works from a windows machine). 

## Additional context
Ubuntu 20.04 LTS

[bug]

### PR DESCRIPTION
**Pull request by anishprasad01**
Fixes #2389

Version 3.x of Ngrok makes changes to the config file format and the supported command line arguments. The `path` field has been removed from the arguments, while the `region` field has been moved to the config file (where it is now required rather than optional). This causes the existing version of Emulator to fail when attempting to spawn Ngrok and connect to a remote bot.

This PR updates `ngrok.ts` and `ngrokService.ts` to remove the `path` and `region` fields so they are not passed to the Ngrok instance, thereby allowing Ngrok v3 to be used with Emulator.

Specific Changes:
- Remove path and region from from `NgrokOptions`.
- Update `ngrokService.ts` to pass the path to the `ngrok.ts` constructor when creating the Ngrok instance instead of passing it as an argument to the instance.
- Update `ngrok.ts` to use the path passed into the constructor instead of the path from `NgrokOptions`.

### CODE REVIEW

**Comment by cwhitten** [comment]
@anishprasad01 thank you for the contribution! would this break using Emulator with ngrok v2?

**Comment by anishprasad01** [comment]
@cwhitten,

I attempted to run with `Ngrok v2.3.0` and was successfully able to connect to a bot hosted in Azure. Since the region field was optional in Ngrok v2, its presence should not break anything. I will perform further testing before this PR gets merged.

**Comment by anishprasad01** [comment]
Testing with both Ngrok v2 and v3 reveals that v2 remains supported even with the modifications made to support v3. Communication with an Azure bot is successful and no errors appear when running or exiting the application. A search of running processes after exiting the application reveals that the Ngrok process is terminated successfully.

Testing with v2:
ngrokv2

Testing with v3:
ngrokv3

**Comment by russorat** [comment]
hi! PM for ngrok here. I'd love to see this PR merged so that we could move your users to the latest version of the ngrok agent. If I can help in any way, please let me know.

**Review by OEvgeny — APPROVED** [review]

**Comment by OEvgeny** [comment]
Build is failing due to the test failures:
```
FAIL packages/app/main/src/ngrok.spec.ts
  ● the ngrok  › ngrok connect/disconnect operations › should throw if it failed to find an ngrok executable at the specified path.

    expect(received).toBe(expected) // Object.is equality

    Expected: "Error: Could not find ngrok executable at path: Applications\\ngrok. Make sure that the correct path to ngrok is configured in the Emulator app settings. Ngrok is required to receive a token from the Bot Framework token service."
    Received: "Error: Could not find ngrok executable at path: D:\\a\\1\\s\\packages\\app\\main\\src\\bin\\ngrok.exe. Make sure that the correct path to ngrok is configured in the Emulator app settings. Ngrok is required to receive a token from the Bot Framework token service."

      225 |         thrown = e;
      226 |       }
    > 227 |       expect(thrown.toString()).toBe(
          |                                 ^
      228 |         `Error: Could not find ngrok executable at path: ${path}. Make sure that the correct path to ngrok is configured in the Emulator app settings. Ngrok is required to receive a token from the Bot Framework token service.`
      229 |       );
      230 |     });

```

**Comment by Giustino98** [comment]
> Build is failing due to the test failures:
> 
> ```
> FAIL packages/app/main/src/ngrok.spec.ts
>   ● the ngrok  › ngrok connect/disconnect operations › should throw if it failed to find an ngrok executable at the specified path.
> 
>     expect(received).toBe(expected) // Object.is equality
> 
>     Expected: "Error: Could not find ngrok executable at path: Applications\\ngrok. Make sure that the correct path to ngrok is configured in the Emulator app settings. Ngrok is required to receive a token from the Bot Framework token service."
>     Received: "Error: Could not find ngrok executable at path: D:\\a\\1\\s\\packages\\app\\main\\src\\bin\\ngrok.exe. Make sure that the correct path to ngrok is configured in the Emulator app settings. Ngrok is required to receive a token from the Bot Framework token service."
> 
>       225 |         thrown = e;
>       226 |       }
>     > 227 |       expect(thrown.toString()).toBe(
>           |                                 ^
>       228 |         `Error: Could not find ngrok executable at path: ${path}. Make sure that the correct path to ngrok is configured in the Emulator app settings. Ngrok is required to receive a token from the Bot Framework token service.`
>       229 |       );
>       230 |     });
> ```

Any update on this? Unfortunately it seems ngrok v2 is not usable anymore and Emulator is not working with any version of Ngrok v3. So, at the moment, it is not possible to contact a remote bot with Emulator.

**Pull request closed without merging**
