### PR TITLE
Fix #1046

### LINKED ISSUE #1046: Manage Service - LUIS url incorrect for westeurope & australiaeast
## Version
v4

## Describe the bug
When using LUIS service hosted outside the US, the incorrect luis URL is being built and sent to the browser.  The URL includes the prefix "www." which gives a DNS error.

## To Reproduce
1.  Attach LUIS service from eu.luis.ai
2. Click on 'Manage Service'
3. Browser opens with Error Code: INET_E_RESOURCE_NOT_FOUND

[bug]

### PR DESCRIPTION
**Pull request by daltskin**
For all LUIS urls - don't include the www as this gives DNS error for westeurope (eu.luis.ai) and australiaeast (au.luis.ai).

Urls should be of format https://eu.luis.ai not https://www.eu.luis.ai as this gives DNS error.

### CODE REVIEW

**Comment by justinwilaby** [comment]
@daltskin - Looks like you'll need to rebase from upstream. I just cleaned up some artifacts left in master that caused linting failures.

**Comment by justinwilaby** [comment]
@daltskin - Looks like the last loose end is to update the unit tests to reflect the new url format. `npm run test` from the project root runs tests in all packages.

**Comment by justinwilaby** [comment]
@daltskin - I'm still seeing a unit test failing in the `servicesExplorerSagas.spec.ts`

**Comment by daltskin** [comment]
Unit tests should be ok now.

**Pull request merged**
